version: '3.9'

services:
  client:
    restart: unless-stopped
    build:
      context: ./client
      args:
        - PUBLIC_API_URL=http://localhost:3000
    ports:
      - '4321:4321'
    volumes:
      - ./client:/home/node/src
      - /home/node/src/node_modules
    depends_on:
      - server

  server:
    restart: unless-stopped
    build:
      context: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/home/node/src
      - /home/node/src/node_modules
    env_file:
      - ./server/.env

  db:
    image: postgres:14.1
    restart: always
    container_name: integration-tests-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    volumes:
      - db:/var/lib/postgresql/data
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db:
    driver: local
  caddy_data:
  caddy_config:
